# Generated by Django 5.1.6 on 2025-02-13 12:56

import django.core.validators
import movies_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movies/posters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Only JPG, JPEG and PNG image formats are allowed'), movies_api.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='movies/trailers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'], message='Only MP4, MOV, AVI and MKV video formats are allowed'), movies_api.validators.validate_file_size]),
        ),
    ]
